$ python bad.py
id=1 Read 0
id=0 Read 0
id=1 Wrote 1
id=0 Wrote 1
id=1 Read 1
id=1 Wrote 2
id=0 Read 2
id=0 Wrote 3
id=1 Read 3
id=1 Wrote 4
id=0 Read 4
id=0 Wrote 5
id=0 Read 5
Exception in thread Thread-2 (accumulate):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
id=0 Wrote 6
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ctrudeau/s/RealPython/032_contmgr/code/race/bad.py", line 10, in accumulate
    balance = int(f.read())
              ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
id=0 Read 6
id=0 Wrote 7
